#!/usr/bin/env bash
# "To infinity and beyond" indefinitely displayed together with
#+ a sleep 2 in between each iteration.
#  "I am invincible!!!" displayed in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
