#!/usr/bin/env bash
# Displays the file contents in `/etc/passwd`
#   Only displays the user home directory path, username and user id.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
