#!/usr/bin/env bash
# Parses Apache list of log files .
#   Visitors by IP and HTTP status code.
#   Shows the number of occurrences, IP, and HTTP status
#  and code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
