#!/usr/bin/env bash
# "Best School" using while loop 10 times.
#  Displays "Hi" before "Best School" on the 9 iteration.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
